name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
jobs:
  Build_IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: stable
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: |
          mkdir -p /Users/runner/work/PicaComic/PicaComic/build/ios/iphoneos/Payload
          mv /Users/runner/work/PicaComic/PicaComic/build/ios/iphoneos/Runner.app /Users/runner/work/PicaComic/PicaComic/build/ios/iphoneos/Payload
          cd /Users/runner/work/PicaComic/PicaComic/build/ios/iphoneos/
          zip -r app-ios.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: app-ios.ipa
          path: /Users/runner/work/PicaComic/PicaComic/build/ios/iphoneos/app-ios.ipa
  Build_MacOS:
    runs-on: macos-15.6
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:        
          architecture: x64
          channel: stable
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
      - run: flutter pub get
      - run: flutter build macos --release
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build.zip
          path: build/macos/Build/Products/Release/pica_comic.app
